#ifndef __EYRIE_CALL_H__
#define __EYRIE_CALL_H__

#define RUNTIME_SYSCALL_UNKNOWN             1000
#define RUNTIME_SYSCALL_OCALL               1001
#define RUNTIME_SYSCALL_SHAREDCOPY          1002
#define RUNTIME_SYSCALL_ATTEST_ENCLAVE      1003
#define RUNTIME_SYSCALL_GET_SEALING_KEY     1004
#define RUNTIME_SYSCALL_SLOTTEE_MINT_CAP    1005
#define RUNTIME_SYSCALL_SLOTTEE_LT_SPAWN    1006
#define RUNTIME_SYSCALL_SLOTTEE_LT_WAIT_VALUE 1007
#define RUNTIME_SYSCALL_EXIT                1101

#define SLOTTEE_LT_WAIT_OP_EQ          0
#define SLOTTEE_LT_WAIT_OP_GE          1
#define SLOTTEE_LT_WAIT_RESULT_READY   0
#define SLOTTEE_LT_WAIT_RESULT_BLOCKED 1

#endif  // __EYRIE_CALL_H__
