//******************************************************************************
// Copyright (c) 2018, The Regents of the University of California (Regents).
// All Rights Reserved. See LICENSE for license details.
//------------------------------------------------------------------------------
#include "edge_wrapper.h"
#include <string.h>
#include "verifier/report.h"
/* Really all of this file should be autogenerated, that will happen
   eventually. */

#define OCALL_PRINT_BUFFER 1
#define OCALL_PRINT_VALUE 2
#define OCALL_COPY_REPORT 3
#define OCALL_GET_STRING 4
#define OCALL_COPY_SLOT_CAP 5
#define OCALL_REPORT_MULTIHART_TICKET 6
#define OCALL_GET_MULTIHART_TICKET_CONFIG 7
#define OCALL_EDGECALL_STRESS_ECHO 8
#define OCALL_EDGECALL_STRESS_REPORT 9

static struct slottee_edgecall_stress_report copied_edgecall_stress_report;
static struct slottee_edgecall_stress_payload copied_edgecall_stress_payload;
static uintptr_t edgecall_stress_echo_count;

void
edge_init(Keystone::Enclave* enclave) {
  enclave->registerOcallDispatch(incoming_call_dispatch);
  register_call(OCALL_PRINT_BUFFER, print_buffer_wrapper);
  register_call(OCALL_PRINT_VALUE, print_value_wrapper);
  register_call(OCALL_COPY_REPORT, copy_report_wrapper);
  register_call(OCALL_GET_STRING, get_host_string_wrapper);
  register_call(OCALL_COPY_SLOT_CAP, copy_slot_cap_wrapper);
  register_call(OCALL_REPORT_MULTIHART_TICKET,
      copy_multihart_ticket_report_wrapper);
  register_call(OCALL_GET_MULTIHART_TICKET_CONFIG,
      get_multihart_ticket_config_wrapper);
  register_call(OCALL_EDGECALL_STRESS_ECHO, copy_edgecall_stress_payload_wrapper);
  register_call(OCALL_EDGECALL_STRESS_REPORT,
      copy_edgecall_stress_report_wrapper);

  edge_call_init_internals(
      (uintptr_t)enclave->getSharedBuffer(), enclave->getSharedBufferSize());
}

void
reset_edgecall_stress_state(void)
{
  memset(&copied_edgecall_stress_report, 0, sizeof(copied_edgecall_stress_report));
  memset(&copied_edgecall_stress_payload, 0, sizeof(copied_edgecall_stress_payload));
  edgecall_stress_echo_count = 0;
}

uintptr_t
get_edgecall_stress_echo_count(void)
{
  return edgecall_stress_echo_count;
}

void
get_edgecall_stress_report(struct slottee_edgecall_stress_report* report)
{
  if (report)
    *report = copied_edgecall_stress_report;
}

void
print_buffer_wrapper(void* buffer) {
  /* For now we assume the call struct is at the front of the shared
   * buffer. This will have to change to allow nested calls. */
  struct edge_call* edge_call = (struct edge_call*)buffer;

  uintptr_t call_args;
  unsigned long ret_val;
  size_t arg_len;
  if (edge_call_args_ptr(edge_call, &call_args, &arg_len) != 0) {
    edge_call->return_data.call_status = CALL_STATUS_BAD_OFFSET;
    return;
  }

  ret_val = print_buffer((char*)call_args);

  // We are done with the data section for args, use as return region
  // TODO safety check?
  uintptr_t data_section = edge_call_data_ptr();

  memcpy((void*)data_section, &ret_val, sizeof(unsigned long));

  if (edge_call_setup_ret(
          edge_call, (void*)data_section, sizeof(unsigned long))) {
    edge_call->return_data.call_status = CALL_STATUS_BAD_PTR;
  } else {
    edge_call->return_data.call_status = CALL_STATUS_OK;
  }

  return;
}

void
print_value_wrapper(void* buffer) {
  /* For now we assume the call struct is at the front of the shared
   * buffer. This will have to change to allow nested calls. */
  struct edge_call* edge_call = (struct edge_call*)buffer;

  uintptr_t call_args;
  unsigned long ret_val;
  size_t args_len;
  if (edge_call_args_ptr(edge_call, &call_args, &args_len) != 0) {
    edge_call->return_data.call_status = CALL_STATUS_BAD_OFFSET;
    return;
  }

  print_value(*(unsigned long*)call_args);

  edge_call->return_data.call_status = CALL_STATUS_OK;
  return;
}

void
copy_report_wrapper(void* buffer) {
  /* For now we assume the call struct is at the front of the shared
   * buffer. This will have to change to allow nested calls. */
  struct edge_call* edge_call = (struct edge_call*)buffer;

  uintptr_t data_section;
  unsigned long ret_val;
  // TODO check the other side of this
  if (edge_call_get_ptr_from_offset(
          edge_call->call_arg_offset, sizeof(report_t), &data_section) != 0) {
    edge_call->return_data.call_status = CALL_STATUS_BAD_OFFSET;
    return;
  }

  copy_report((void*)data_section);

  edge_call->return_data.call_status = CALL_STATUS_OK;

  return;
}

void
copy_slot_cap_wrapper(void* buffer) {
  struct edge_call* edge_call = (struct edge_call*)buffer;
  uintptr_t call_args;
  size_t args_len;

  if (edge_call_args_ptr(edge_call, &call_args, &args_len) != 0 ||
      args_len != sizeof(struct slot_cap_t)) {
    edge_call->return_data.call_status = CALL_STATUS_BAD_OFFSET;
    return;
  }

  copy_slot_cap((void*)call_args, args_len);
  edge_call->return_data.call_status = CALL_STATUS_OK;
}

void
copy_multihart_ticket_report_wrapper(void* buffer) {
  struct edge_call* edge_call = (struct edge_call*)buffer;
  uintptr_t call_args;
  size_t args_len;

  if (edge_call_args_ptr(edge_call, &call_args, &args_len) != 0 ||
      args_len != sizeof(struct slottee_multihart_ticket_report)) {
    edge_call->return_data.call_status = CALL_STATUS_BAD_OFFSET;
    return;
  }

  copy_multihart_ticket_report((void*)call_args, args_len);
  edge_call->return_data.call_status = CALL_STATUS_OK;
}

static void
copy_edgecall_stress_payload(void* buffer, size_t size) {
  if (size == sizeof(copied_edgecall_stress_payload)) {
    memcpy(&copied_edgecall_stress_payload, buffer, size);
    __sync_fetch_and_add(&edgecall_stress_echo_count, 1);
  }
}

void
copy_edgecall_stress_payload_wrapper(void* buffer) {
  struct edge_call* edge_call = (struct edge_call*)buffer;
  uintptr_t call_args;
  size_t args_len;

  if (edge_call_args_ptr(edge_call, &call_args, &args_len) != 0 ||
      args_len != sizeof(struct slottee_edgecall_stress_payload)) {
    edge_call->return_data.call_status = CALL_STATUS_BAD_OFFSET;
    return;
  }

  copy_edgecall_stress_payload((void*)call_args, args_len);
  if (edge_call_setup_ret(edge_call, (void*)call_args, args_len)) {
    edge_call->return_data.call_status = CALL_STATUS_BAD_PTR;
  } else {
    edge_call->return_data.call_status = CALL_STATUS_OK;
  }
}

static void
copy_edgecall_stress_report(void* buffer, size_t size) {
  if (size == sizeof(copied_edgecall_stress_report))
    memcpy(&copied_edgecall_stress_report, buffer, size);
}

void
copy_edgecall_stress_report_wrapper(void* buffer) {
  struct edge_call* edge_call = (struct edge_call*)buffer;
  uintptr_t call_args;
  size_t args_len;

  if (edge_call_args_ptr(edge_call, &call_args, &args_len) != 0 ||
      args_len != sizeof(struct slottee_edgecall_stress_report)) {
    edge_call->return_data.call_status = CALL_STATUS_BAD_OFFSET;
    return;
  }

  copy_edgecall_stress_report((void*)call_args, args_len);
  edge_call->return_data.call_status = CALL_STATUS_OK;
}

void
get_multihart_ticket_config_wrapper(void* buffer) {
  struct edge_call* edge_call = (struct edge_call*)buffer;
  uintptr_t data_section = edge_call_data_ptr();
  struct slottee_multihart_ticket_config config;

  get_multihart_ticket_config(&config);
  memcpy((void*)data_section, &config, sizeof(config));

  if (edge_call_setup_ret(edge_call, (void*)data_section, sizeof(config))) {
    edge_call->return_data.call_status = CALL_STATUS_BAD_PTR;
  } else {
    edge_call->return_data.call_status = CALL_STATUS_OK;
  }
}

void
get_host_string_wrapper(void* buffer) {
  /* For now we assume the call struct is at the front of the shared
   * buffer. This will have to change to allow nested calls. */
  struct edge_call* edge_call = (struct edge_call*)buffer;

  uintptr_t call_args;
  unsigned long ret_val;
  size_t args_len;
  if (edge_call_args_ptr(edge_call, &call_args, &args_len) != 0) {
    edge_call->return_data.call_status = CALL_STATUS_BAD_OFFSET;
    return;
  }

  const char* host_str = get_host_string();
  size_t host_str_len  = strlen(host_str) + 1;

  // This handles wrapping the data into an edge_data_t and storing it
  // in the shared region.
  if (edge_call_setup_wrapped_ret(edge_call, (void*)host_str, host_str_len)) {
    edge_call->return_data.call_status = CALL_STATUS_BAD_PTR;
  } else {
    edge_call->return_data.call_status = CALL_STATUS_OK;
  }

  return;
}
